In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
l = [4, 5.5, 89, 9]

In [4]:
l

[4, 5.5, 89, 9]

In [5]:
np.array(l)

array([ 4. ,  5.5, 89. ,  9. ])

In [6]:
np.array(l, dtype=np.float32)

array([ 4. ,  5.5, 89. ,  9. ], dtype=float32)

In [7]:
np.asarray([1,2,3])

array([1, 2, 3])

In [8]:
np.array(l)

array([ 4. ,  5.5, 89. ,  9. ])

In [9]:
np.asarray(np.array(l))

array([ 4. ,  5.5, 89. ,  9. ])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(67, 100)

array([67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
np.arange(67, 100, 0.5)

array([67. , 67.5, 68. , 68.5, 69. , 69.5, 70. , 70.5, 71. , 71.5, 72. ,
       72.5, 73. , 73.5, 74. , 74.5, 75. , 75.5, 76. , 76.5, 77. , 77.5,
       78. , 78.5, 79. , 79.5, 80. , 80.5, 81. , 81.5, 82. , 82.5, 83. ,
       83.5, 84. , 84.5, 85. , 85.5, 86. , 86.5, 87. , 87.5, 88. , 88.5,
       89. , 89.5, 90. , 90.5, 91. , 91.5, 92. , 92.5, 93. , 93.5, 94. ,
       94.5, 95. , 95.5, 96. , 96.5, 97. , 97.5, 98. , 98.5, 99. , 99.5])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.ones((5, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [16]:
np.array(np.array((10,29,3)))

array([10, 29,  3])

In [17]:
np.ones_like(5)

array(1)

In [18]:
np.ones_like([5, 4])

array([1, 1])

In [19]:
np.ones_like([[5.4, 4], [8, 9]])

array([[1., 1.],
       [1., 1.]])

In [20]:
np.ones_like([[[5., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [11., 1.],
        [1., 1.]],

       [[12., 1.],
        [13., 1.],
        [15., 1.]],

       [[1., 1.],
        [1., 5.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [21]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((6, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.zeros_like([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [24]:
np.empty(12)

array([1.00482955e-311, 3.16202013e-322, 0.00000000e+000, 0.00000000e+000,
       1.14587773e-312, 3.53790670e-057, 7.87630593e-071, 7.69149961e+169,
       3.93628829e-062, 3.11023025e+179, 1.60025725e+160, 6.29082725e-066])

In [25]:
np.empty_like([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

array([[[1.00481761e-311, 1.01283457e-321],
        [0.00000000e+000, 0.00000000e+000],
        [1.89146896e-307, 1.16097020e-028]],

       [[1.26087994e-076, 2.92732918e-028],
        [1.39736859e-076, 1.04917183e-153],
        [5.23081515e-143, 8.70227457e-071]],

       [[2.58142390e-057, 1.86923640e-051],
        [1.13073934e-042, 1.70098498e+256],
        [5.49109388e-143, 1.06396443e+224]],

       [[3.96041428e+246, 1.16318408e-028],
        [8.39388494e+165, 9.14066852e-043],
        [7.32118088e+169, 2.58267829e-057]],

       [[1.01848862e+248, 1.16096643e-028],
        [9.80058441e+252, 7.50189709e+247],
        [1.14484251e+243, 2.59903827e-144]]])

In [26]:
np.empty_like([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]]).shape

(5, 3, 2)

In [27]:
np.eye(5, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.identity(5, dtype=np.int16)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int16)

In [29]:
np.full(5, fill_value=9)

array([9, 9, 9, 9, 9])

In [30]:
np.full((5, 4), fill_value=3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [31]:
np.full_like([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]], fill_value=6)

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])